# Generated by Django 3.2 on 2021-04-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loop',
            name='loop_data',
        ),
        migrations.AddField(
            model_name='loop',
            name='bpm',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='loop',
            name='steps',
            field=models.CharField(default='C3', max_length=2000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loop',
            name='synth',
            field=models.CharField(default='fmSynth', max_length=50),
        ),
    ]
