# Generated by Django 3.2 on 2021-04-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loop',
            name='effect',
            field=models.CharField(default='freeverb', max_length=500),
        ),
    ]
