# Generated by Django 3.2 on 2021-04-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loops', '0002_alter_loop_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='loop',
            name='scale',
            field=models.CharField(default='major', max_length=50),
        ),
    ]
