# Generated by Django 3.2 on 2021-04-16 14:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loops', '0002_loop_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loop',
            name='loop_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
