# Generated by Django 3.2 on 2021-04-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('loops', '0002_alter_loop_effect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loop',
            name='genres',
            field=models.ManyToManyField(related_name='loops', to='genres.Genre'),
        ),
    ]
