# Generated by Django 3.2 on 2021-04-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loops', '0003_alter_loop_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='loop',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
