# Generated by Django 3.2 on 2021-04-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loops', '0003_loop_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='loop',
            name='effect',
            field=models.CharField(default='freeverb', max_length=50),
        ),
    ]
