# Generated by Django 3.2 on 2021-04-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loops', '0003_alter_loop_loop_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loop',
            name='loop_data',
            field=models.TextField(max_length=5000),
        ),
    ]
