# Generated by Django 3.2 on 2021-04-17 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loops', '0004_alter_loop_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loop',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loops', to=settings.AUTH_USER_MODEL),
        ),
    ]
