# Generated by Django 3.2 on 2021-04-16 16:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loops', '0009_alter_loop_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loop',
            name='steps',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8), size=8),
        ),
    ]
